language: julia
os:
  - linux
  - osx
  - windows
julia:
  - nightly
  - 1.0
  - 1.5
notifications:
  email: false
codecov: true
coveralls: true
branches:
  only:
    - master
jobs:
  allow_failures:
    - julia: nightly
