name = "RecordedArrays"
uuid = "1040807a-3a2f-4266-b2c1-805b33c7034a"
authors = ["Long Wang <wangl.cc@outlook.com>"]
version = "0.3.0"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
ResizingTools = "112dcb92-135b-4fff-bdeb-bacebdb79ec0"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
ArrayInterface = "3.1.2"
RecipesBase = "1.1"
ResizingTools = "0.3.4"
Static = "0.3, 0.4"
julia = "1.2"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "BenchmarkTools"]
