name = "RecordedArrays"
uuid = "1040807a-3a2f-4266-b2c1-805b33c7034a"
authors = ["Long Wang <wangl.cc@outlook.com>"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
julia = "1.0"
RecipesBase = "1.1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "BenchmarkTools"]
