name = "RecordedArray"
uuid = "1040807a-3a2f-4266-b2c1-805b33c7034a"
authors = ["Long Wang <wangl.cc@outlook.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
