name: Deploy Documentation

on:
  push:
    branches:
      - master
    paths:
      - "src"
      - "test"
      - "docs"
      - "Project.toml"

jobs:
  docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}

# vim:ts=2:sw=2
