name: Format Check

on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
        - opened
        - synchronize
        - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install JuliaFormatter
        run: |
          julia  -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter"))'
      - name: Format check
        run: |
          julia -e '
          using JuliaFormatter
          if format(".", BlueStyle())
              exit(0)
          else
              exit(1)
          end'
